image: ruby:2.3

variables:
  JEKYLL_ENV: production
  PAGES_REPO_NWO: $CI_PROJECT_PATH

pages:
  script:
  - bundle install
  - bundle exec jekyll serve
  artifacts:
    paths:
    - public
  only:
  - master
