theme: jekyll-theme-hacker

title: [hypnotortoise.gitlab.io]
description: [ Thanks for stopping by ]

timezone: Europe/Berlin
encoding: utf-8

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

show_downloads: ["false"]
