theme: jekyll-theme-hacker

title: [hypnotortoise.github.io]
description: [ Thanks for stopping by ]

timezone: Europe/Berlin
encoding: utf-8

exclude: [vendor, "Gemfile", "Gemfile.lock"] # make sure to exclude 'vendor' and Gemfiles from the build

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

site.show_downloads: ["false"]
